name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  code-style:
    name: Code style check
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Prepare Powershell
        run:
          powershell -Command "& {Invoke-ScriptAnalyzer -Path '.\script.ps1}"

